### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [Olesya01/prj-rev-bwfs-dasmoto#5]
Overall, your work met the project specifications -- good job!

Besides the path issue, my comments were about style and formatting. Your actual web design was on point. I encourage you to pay more attention to formatting though. Comment your code and add more spacing. Also, check for typos (you had 1 or 2).

**Comment by Olesya01** [comment]
Thanks for the review! It really helped! I went ahead and made the necessary changes.
